//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMD_Project.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Alert
    {
        [Key]
        public int AlertID { get; set; }

        public Nullable<int> PatientID { get; set; }
        public string AlertType { get; set; }
        public Nullable<int> MetricID { get; set; }
        public Nullable<System.DateTime> AlertDate { get; set; }
        public string Status { get; set; }
        public string DoctorAction { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual HealthMetric HealthMetric { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
