//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMD_Project.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class WearableDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WearableDevice()
        {
            this.HealthMetrics = new HashSet<HealthMetric>();
        }
        [Key]
        public int DeviceID { get; set; }
        [ForeignKey("Patient")]
        public Nullable<int> PatientID { get; set; }
        public string DeviceType { get; set; }
        public string DeviceSerialNumber { get; set; }
        public Nullable<System.DateTime> LastSync { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthMetric> HealthMetrics { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
